### ISSUE TITLE
Cell packing density as a unit.

### ISSUE THREAD

**Issue by russelljjarvis** [apdavison/nineml#10]
Should cell packing density per volume be a unit, ie  cells/mm^{3}?

**Comment by apdavison** [comment]
Please could you move this issue to either [INCF/nineml](https://github.com/INCF/nineml) (if it concerns the specification) or [INCF/lib9ML](https://github.com/INCF/lib9ML) (if it concerns the Python library)?

**Comment by russelljjarvis** [comment]
Yes, sure. Sorry.
